name: adv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python
  - tensorflow
  - numpy
  - matplotlib
  - pylint
  - yapf
  - notebook
  - jupyterlab
  - pytorch
  - torchvision
  - opencv
  - cudatoolkit=10.1
  - tqdm
  - pip
  - pip:
    - foolbox
    - ipywidgets
