name: adv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3
  - tensorflow
  - numpy
  - matplotlib
  - pylint
  - yapf
  - notebook
  - jupyterlab=1.2
  - pytorch
  - torchvision
  - opencv
  - cudatoolkit=10.1
  - tqdm
  - pip
  - nodejs
  - jupyterlab_code_formatter
  - python-language-server
  - pip:
      - foolbox
      - ipywidgets
      - halo
