name: adversarial-attacks
channels:
  - pytorch
  - defaults
dependencies:
  - python
  - tensorflow
  - numpy
  - matplotlib
  - pylint
  - autopep8
  - notebook
  - pytorch
  - torchvision
  - cudatoolkit=10.1
  - pip
  - pip:
    - foolbox
    - barbar
    - pkbar
