name: adv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python
  - tensorflow
  - numpy
  - matplotlib
  - pylint
  - autopep8
  - notebook
  - pytorch
  - torchvision
  - cudatoolkit=10.1
  - tqdm
  - pip
  - pip:
    - foolbox
    - ipywidgets
